spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password:

webClient:
  external:
    supplier:
      base-url: http://localhost:8090
  connection:
    timeout: 5000
  retry: 3